server:
  port: 8089


spring:
  application:
    name: gateway
  cloud:
    consul:  #注册
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes: #路由
        - id: user_route  #唯一id
          uri: lb://users  #服务的端口
          predicates:
            - Path=/user/**

        - id: emps_route
          uri: lb://emps
          predicates:
            - Path=/emp/**
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true